# Generated by Django 3.2.5 on 2021-07-16 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('name', models.CharField(max_length=64, verbose_name='仓库类型名称')),
            ],
            options={
                'verbose_name': '仓库类型',
                'db_table': 'w_wharehouse_type',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('wh_no', models.CharField(max_length=64, verbose_name='仓库编号')),
                ('wh_name', models.CharField(max_length=1024, verbose_name='仓库名')),
                ('wh_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='w_warehouse.warehousetype', verbose_name='仓库类型')),
            ],
            options={
                'verbose_name': '仓库信息',
                'db_table': 'w_wharehouse',
            },
        ),
    ]
