# Generated by Django 3.2.5 on 2021-07-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='终止合作时间'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='memo',
            field=models.CharField(max_length=128, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='start_date',
            field=models.DateField(blank=True, verbose_name='合作时间'),
        ),
    ]
